doctrine:
    dbal:
      default_connection: mysql
      connections:                      
        ### importante hay algo en el procesamiento de las conexiones, increiblemente lo gice funcionar 
        ### cambiando el orden
        trimu:
          url: '%env(resolve:TRIMU_URL)%'
          driver: oci8    
        mysql:
          url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'      
    orm:
        auto_generate_proxy_classes: true        
        default_entity_manager: mysql
        
        entity_managers:
          trimu:                        
            connection: trimu
            naming_strategy: doctrine.orm.naming_strategy.underscore
            mappings:
              trimu:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity/AdminTRIMU'
                prefix: 'App\Entity\AdminTRIMU'
                alias: trimu    
          mysql:                                    
            connection: mysql           
            naming_strategy: doctrine.orm.naming_strategy.underscore
            auto_mapping: true
            mappings:
              App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App          